ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "Shift"
ADD COLUMN "startLat" DOUBLE PRECISION,
ADD COLUMN "startLng" DOUBLE PRECISION,
ADD COLUMN "endLat" DOUBLE PRECISION,
ADD COLUMN "endLng" DOUBLE PRECISION,
ADD COLUMN "accuracy" DOUBLE PRECISION;
